#!/bin/bash
grep notify `find . -name \*.php` | grep NOTIF | sed "s/notify[ ]*(/notify(/" | sed "s/.*->notify('//" | sed "s/',.*$//"  | sed "s/');//" | grep -v zen_ | grep -v "includes/" | sed "s///g" | sort | uniq 
